version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb:/home/dynamodblocal/data

  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./auth_service/src:/app/auth_service
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  frontend:
    build:
      context: ./web_client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web_client:/app
    environment:
      REACT_APP_AUTH_SERVICE_URL: ${REACT_APP_AUTH_SERVICE_URL}
      REACT_APP_PROFILE_SERVICE_URL: ${REACT_APP_PROFILE_SERVICE_URL}

volumes:
  postgres_data: