AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  profile_service

  Sample SAM Template for profile_service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  GetProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create_profile.handler
      Runtime: python3.9
      Events:
        GetProfile:
          Type: Api
          Properties:
            Path: /profile
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetProfileApi:
    Description: "API Gateway endpoint URL for Prod stage for GetProfile function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/profile/"
  GetProfileFunction:
    Description: "GetProfile Lambda Function ARN"
    Value: !GetAtt GetProfileFunction.Arn
  GetProfileFunctionIamRole:
    Description: "Implicit IAM Role created for GetProfile function"
    Value: !GetAtt GetProfileFunctionRole.Arn
